name: Actualizar GeoJSON

on:
  schedule:
    - cron: '*/20 * * * *'  # Cada 20 minutos
  workflow_dispatch:        # Permite ejecución manual

permissions:
  contents: write           # Concede permisos de escritura explícitos al GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Permite usar GITHUB_TOKEN en git push
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de lectura
        env:
          API_KEY_PURPLEAIR: ${{ secrets.API_KEY_PURPLEAIR }}
        run: |
          python script.py

      - name: Guardar y subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-actualización de archivos GeoJSON"
          git push origin main
